/** Synthetic test fixtures only; these identities and awards are never production data. */
import type { AcceptedMilestone, Contribution, DecisionEvent, FamilyRecord, GradingContext, StageAssessment } from '../src/contracts.ts';
import { DEFAULT_PROFILE, type GradingInput } from '../src/grading.ts';
import { sha256 } from '../src/hash.ts';
export const family = (id = 'family-test', seed = false, seed_baseline: FamilyRecord['seed_baseline'] = 0): FamilyRecord => ({ id, rubric_version: '0.1', scope: 'Synthetic acceptance boundary.', acceptance_test: 'A test checks a bounded distinct outcome.', aliases: [], predecessor_family_ids: [], excluded_overlap: [], seed, seed_baseline });
export function event(sequence: number, tier: DecisionEvent['cumulative_tier'], github_id = 101, overrides: Partial<DecisionEvent> = {}): DecisionEvent {
  return { schema_version: '1.0', id: `event-${sequence}`, sequence, kind: tier === 0 ? 'assess_zero' : sequence === 1 ? 'award' : 'upgrade', family_id: 'family-test', rubric_version: '0.1', category: 'experiments', repository_id: 1001, pr_number: sequence, milestone_id: `milestone-${sequence}`, earned_at: `2026-09-${String(sequence).padStart(2, '0')}T12:00:00.000Z`, posted_at: `2026-09-${String(sequence).padStart(2, '0')}T12:10:00.000Z`, assessment_id: `assessment-${sequence}`, artifact_binding_digest: 'a'.repeat(64), authority_receipt_ref: 'synthetic-authenticated-test-receipt', cumulative_tier: tier, ...(tier ? { allocation_shares: [{ github_id, share_basis_points: 10000, status: 'paid' as const, acknowledgment_receipt_ref: 'synthetic-ack' }] } : {}), reason: 'Synthetic test decision only.', ...overrides };
}
export const milestones = (events: DecisionEvent[]): AcceptedMilestone[] => events.filter(e => !e.target_event_id).map(e => ({ id: e.milestone_id, family_id: e.family_id, repository_id: e.repository_id, pr_number: e.pr_number, earned_at: e.earned_at, depends_on: [] }));
export const trusted = (events: DecisionEvent[]) => ({ verifyDecision: () => true, accepted_milestones: milestones(events) });
export const contribution: Contribution = { schema_version: '1.0', id: 'test-direction', kind: 'direction', title: 'Synthetic useful direction', summary: 'A test-only suggestion with specific evidence.', branch_ids: ['branch-test'], contributors: [{ github_id: 101, github_login: 'synthetic-fixture', roles: ['Conceptualization'] }], ai_usage: { status: 'none', tools: [], reproducibility_notes: '' }, changes: [{ path: 'research/example.md', improvement: 'A test-only useful suggestion.' }], outcomes: [{ id: 'outcome-test', family_id: 'family-test', before: 'No test direction.', after: 'A specific test direction.', acceptance_test: 'Inspect rationale, prior-work check and first step.', evidence: ['research/example.md'], related_outcomes: [], claimed_cumulative_tier: 2, claimed_incremental_points: 2, claim_rationale: 'A bounded distinct suggestion.', attribution: [{ github_id: 101, share_basis_points: 10000 }] }], claimed_total_points: 2, rubric_version: '0.1', conflicts: [], limitations: ['Test-only synthetic data.'], rights_manifest: 'research/rights.md' };
export const assessment = (tier: StageAssessment['outcomes'][number]['assessed_tier'] = 2): StageAssessment => ({ schema_version: '1.0', admission_action: 'accept', score_status: 'proposed', conduct_status: 'clear', findings: [], outcomes: [{ family_id: 'family-test', scope: 'Test direction scope.', category: 'proposals', predecessors: [], aliases: [], claimed_tier: 2, assessed_tier: tier, gate_evidence: Array.from({ length: 7 }, (_, i) => ({ gate: `G${i + 1}`, status: 'pass', evidence_refs: ['research/example.md'], reason: 'Synthetic evidence anchor for unit testing.' })), attribution_status: 'verified', reason: 'Test-only rationale.' }], inspected_paths: ['research/example.md', 'research/rights.md'], inspection_gaps: [], next_action: 'Proceed to independently verified broker checks.', appeal_route: 'A linked evidence-based appeal PR.' });
export async function gradingInput(): Promise<GradingInput> {
  const files = await Promise.all(['research/example.md', 'research/rights.md'].map(async path => { const content = path.endsWith('rights.md') ? 'Original synthetic test material; no external source claims.' : 'Question: test spaces versus tokens. Rationale: isolate a boundary. Prior-work check: synthetic fixture only. First step: inspect a declared example.'; return { path, content, sha256: await sha256(content), byte_length: new TextEncoder().encode(content).byteLength, media_type: 'text/markdown', inspection: 'complete' as const }; }));
  const context: GradingContext = { schema_version: '1.0', repository_id: 1001, pr_number: 1, head_sha: 'a'.repeat(40), base_sha: 'b'.repeat(40), rules_version: '0.1', rubric_version: '0.1', evaluator_commit: 'c'.repeat(40), families: [family()], credit_high_water_tiers: { 'family-test': 0 }, ledger_digest: 'd'.repeat(64), public_evidence: [], acknowledgment_receipts: [], execution_receipts: [] };
  return { contribution: structuredClone(contribution), files, context, profile: { ...DEFAULT_PROFILE, status: 'calibration', model_id: 'synthetic-test-model' }, policy: { rules: 'Synthetic test rules.', rubric: 'Synthetic test rubric.', methodology: 'Synthetic test methodology.' } };
}
