import test from 'node:test';
import assert from 'node:assert/strict';
import { buildLeaderboard, periodBounds, replayLedger } from '../src/ledger.ts';
import { event, family, trusted } from './fixtures.ts';

test('direction, protocol and research progression conserves 2 + 3 + 5 across people', () => { const events = [event(1, 2, 101), event(2, 5, 102), event(3, 10, 103)]; const state = replayLedger(events, [family()], trusted(events)); assert.deepEqual(state.public_awards.map(a => a.units), [20000, 30000, 50000]); assert.equal(state.paid_units, 100000); });
test('proposal then study earns 2 + 8', () => { const events = [event(1, 2), event(2, 10, 102)]; assert.deepEqual(replayLedger(events, [family()], trusted(events)).public_awards.map(a => a.units), [20000, 80000]); });
test('later outcome cannot settle before earlier merged predecessor', () => { const earlier = event(2, 5, 101, { id: 'earlier', milestone_id: 'early', earned_at: '2026-09-01T12:00:00Z' }); const later = event(1, 10, 102, { earned_at: '2026-09-02T12:00:00Z', posted_at: '2026-09-03T12:00:00Z' }); assert.throws(() => replayLedger([later, earlier], [family()], trusted([earlier, later])), /earlier accepted milestone/); });
test('delivery order never changes event sequence replay', () => { const events = [event(1, 5), event(2, 10, 102)]; assert.deepEqual(replayLedger([...events].reverse(), [family()], trusted(events)), replayLedger(events, [family()], trusted(events))); });
test('seed 10 occupies baseline with zero competitive allocation and 20 upgrade earns 10', () => { const events = [event(1, 20)]; const state = replayLedger(events, [family('family-test', true, 10)], trusted(events)); assert.equal(state.paid_units, 100000); assert.equal(state.families['family-test']!.seed_occupied_units, 100000); });
test('unassessed seed is a hold rather than a free zero baseline', () => { const events = [event(1, 5)]; assert.throws(() => replayLedger(events, [family('family-test', true, null)], trusted(events)), /Resolve this seed baseline/); });
test('alias cannot refill consumed ladder', () => { const f = family(); f.aliases = ['alias']; const events = [event(1, 20), event(2, 20, 102, { family_id: 'alias', allocation_shares: [] })]; const state = replayLedger(events, [f], trusted(events)); assert.equal(state.paid_units, 200000); });
test('duplicate canonical family within one accepted PR is rejected', () => { const events = [event(1, 2), event(2, 10, 102, { pr_number: 1 })]; assert.throws(() => replayLedger(events, [family()], trusted(events)), /One canonical family milestone/); });
test('joint 33.33/66.67 percent is exact 16665 and33335 units', () => { const events = [event(1, 5, 101, { allocation_shares: [{ github_id: 101, share_basis_points: 3333, status: 'paid', acknowledgment_receipt_ref: 'ack-a' }, { github_id: 102, share_basis_points: 6667, status: 'paid', acknowledgment_receipt_ref: 'ack-b' }] })]; assert.deepEqual(replayLedger(events, [family()], trusted(events)).public_awards.map(a => a.units), [16665, 33335]); });
test('disputed 40 percent is held and never ranks', () => { const events = [event(1, 5, 101, { allocation_shares: [{ github_id: 101, share_basis_points: 6000, status: 'paid', acknowledgment_receipt_ref: 'ack' }, { reservation_id: 'dispute', share_basis_points: 4000, status: 'held' }] })]; const state = replayLedger(events, [family()], trusted(events)); assert.equal(state.paid_units, 30000); assert.equal(state.held_units, 20000); assert.equal(state.public_awards.length, 1); });
test('unacknowledged paid allocation cannot mint points', () => { const events = [event(1, 5, 101, { allocation_shares: [{ github_id: 101, share_basis_points: 10000, status: 'paid' }] })]; assert.throws(() => replayLedger(events, [family()], trusted(events)), /responsibility acknowledgment/); });
test('correction A10 to5 leaves B10 and5withdrawn withhighwater20', () => { const a = event(1, 10); const b = event(2, 20, 102); const correction = { ...event(3, 20), kind: 'correct' as const, target_event_id: a.id, earned_at: a.earned_at, pr_number: a.pr_number, milestone_id: a.milestone_id, allocation_shares: undefined, replacement_allocations: [{ github_id: 101, units: 50000, status: 'paid' as const, acknowledgment_receipt_ref: 'ack' }] }; delete correction.allocation_shares; const events = [a, b, correction]; const state = replayLedger(events, [family()], trusted(events)); assert.deepEqual(state.public_awards.map(x => x.units), [50000, 100000]); assert.equal(state.withdrawn_units, 50000); assert.equal(state.families['family-test']!.credit_high_water_tier, 20); });
test('correction cannot award a windfall to someone else', () => { const a = event(1, 10); const correction = { ...event(2, 10), kind: 'correct' as const, target_event_id: a.id, earned_at: a.earned_at, pr_number: a.pr_number, milestone_id: a.milestone_id, allocation_shares: undefined, replacement_allocations: [{ github_id: 102, units: 50000, status: 'paid' as const, acknowledgment_receipt_ref: 'ack' }] }; delete correction.allocation_shares; assert.throws(() => replayLedger([a, correction], [family()], trusted([a, correction])), /cannot transfer/); });
test('tier20 and distinct successor10 can conserve30 across separate scopes', () => { const predecessor = family(); const successor = { ...family('successor'), predecessor_family_ids: ['family-test'], excluded_overlap: ['Original hypothesis class excluded.'] }; const events = [event(1, 20), event(2, 10, 102, { family_id: 'successor' })]; assert.equal(replayLedger(events, [predecessor, successor], trusted(events)).paid_units, 300000); });
test('no receipt verifier means no authority', () => { const events = [event(1, 5)]; assert.throws(() => replayLedger(events, [family()], { accepted_milestones: trusted(events).accepted_milestones }), /verified delegated authority/); });
test('forged authority and missing merge history fail closed', () => { const events = [event(1, 5)]; assert.throws(() => replayLedger(events, [family()], { ...trusted(events), verifyDecision: () => false }), /authority/); assert.throws(() => replayLedger(events, [family()], { verifyDecision: () => true }), /trusted accepted-research/); });
test('rubric shopping does not reset a family', () => { const events = [event(1, 5, 101, { rubric_version: '2.0' })]; assert.throws(() => replayLedger(events, [family()], trusted(events)), /rubric is pinned/); });
test('UTC weeks begin Monday and months are calendar half-open intervals', () => { assert.deepEqual(periodBounds('week', '2026-09-06T23:59:59Z'), { start: '2026-08-31T00:00:00.000Z', end: '2026-09-07T00:00:00.000Z' }); assert.deepEqual(periodBounds('month', '2026-12-31T23:59:59Z'), { start: '2026-12-01T00:00:00.000Z', end: '2027-01-01T00:00:00.000Z' }); });
test('exact ties use competition ranks and stable display identity', () => { const events = [event(1, 10, 103, { family_id: 'one' }), event(2, 5, 102, { family_id: 'two' }), event(3, 5, 101, { family_id: 'three' }), event(4, 2, 104, { family_id: 'four' })]; const state = replayLedger(events, ['one', 'two', 'three', 'four'].map(x => family(x)), trusted(events)); const board = buildLeaderboard(state, { as_of: '2026-09-30T00:00:00Z' }); assert.deepEqual(board.map(x => x.rank), [1, 2, 2, 4]); assert.deepEqual(board.map(x => x.github_id), [103, 101, 102, 104]); });
test('identity alias preserves newcomer age and merges credit without duplication', () => { const events = [event(1, 2)]; const state = replayLedger(events, [family()], trusted(events)); const options = { as_of: '2026-09-06T00:00:00Z', identity_aliases: { 101: 102 }, first_substantive_merge: { 101: '2025-01-01T00:00:00Z', 102: '2026-09-01T00:00:00Z' } }; assert.equal(buildLeaderboard(state, options)[0]!.github_id, 102); assert.equal(buildLeaderboard(state, { ...options, newcomer: true }).length, 0); });
test('zero decisions are terminal settled milestones with no leaderboard row', () => { const events = [event(1, 0)]; const state = replayLedger(events, [family()], trusted(events)); assert.equal(state.public_awards.length, 0); assert.equal(state.families['family-test']!.settled_milestones.length, 1); });


test('authorized zero-credit regrade appends only the unoccupied increment on the original milestone', () => {
 const earlier=event(1,5);const zero=event(2,5,102,{allocation_shares:[]});
 const upgrade=event(3,10,102,{target_event_id:zero.id,pr_number:zero.pr_number,milestone_id:zero.milestone_id,earned_at:zero.earned_at,artifact_binding_digest:'b'.repeat(64)});
 const events=[earlier,zero,upgrade];const state=replayLedger(events,[family()],trusted(events));
 assert.deepEqual(state.public_awards.map(a=>[a.pr_number,a.units,a.earned_at]),[[1,50000,earlier.earned_at],[2,50000,zero.earned_at]]);
 assert.equal(state.awards[zero.id]!.original_units,0);assert.equal(state.families['family-test']!.settled_milestones.length,2);
 assert.throws(()=>replayLedger([earlier,zero,{...upgrade,target_event_id:earlier.id}],[family()],trusted(events)),/uncredited milestone/);
 assert.throws(()=>replayLedger([earlier,zero,{...upgrade,artifact_binding_digest:zero.artifact_binding_digest}],[family()],trusted(events)),/uncredited milestone/);
 assert.throws(()=>replayLedger([earlier,zero,{...upgrade,cumulative_tier:5}],[family()],trusted(events)),/uncredited milestone/);
 const repeated={...upgrade,id:'repeat',sequence:4,assessment_id:'another',cumulative_tier:20 as const};
 assert.throws(()=>replayLedger([...events,repeated],[family()],trusted(events)),/uncredited milestone/);
});
