"""Rebuild original seed annotations. Source assertions were inspected on 2026-09-06; this is not a crawler."""
from pathlib import Path
import hashlib
import json
import shutil

ROOT = Path(__file__).resolve().parents[2]
DATE = "2026-09-06"


def save(path, value):
    file = ROOT / path
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main():
    sources = [
        ("yale-overview", "Voynich Manuscript: Beinecke collection overview", "Yale Beinecke Library", "https://beinecke.library.yale.edu/collections/highlights/voynich-manuscript", "custodian", "Custodian introduction and links to manuscript history and scientific examination.", "Reference only. Distinguish overview statements from independently retrieved technical reports.", "verified_web"),
        ("yale-catalog", "Beinecke MS 408 physical description", "Barbara A. Shailor; Yale Beinecke Library", "https://pre1600ms.beinecke.library.yale.edu/docs/pre1600.ms408.HTM", "custodian", "Catalog records physical leaves, foldouts, collation and archival holdings; some dating and ownership assertions reflect older scholarship.", "Original annotations only. Historical catalog wording must not override newer evidence; no plant identification or John Dee attribution is adopted.", "verified_web"),
        ("yale-images", "Beinecke MS 408 official digital object", "Yale Library", "https://collections.library.yale.edu/catalog/2002046", "images", "Official image landing reference; current automated retrieval returned HTTP 403, so no canvas IDs or scan count are claimed.", "Reference only; item-level image rights and exact IIIF mappings remain unresolved.", "access_blocked_403"),
        ("yale-reuse", "Yale Library reuse, permissions and copyright policy", "Yale Library", "https://library.yale.edu/policies/reuse", "rights", "Institutional starting policy for item-specific image reuse assessment.", "Policy reference, not blanket permission to mirror every collection object.", "verified_web"),
        ("zandbergen-transliterations", "Voynich transliteration resources and version table", "René Zandbergen", "https://www.voynich.nu/transcr.html", "transcriptions", "Documents independently produced readings and format/version differences. EVA is a shape representation rather than a recovered language alphabet.", "Reference and attributed original metadata; source-table statistics use specific counting conventions.", "verified_web"),
        ("zandbergen-rights", "voynich.nu copyright and transliteration licensing", "René Zandbergen", "https://voynich.nu/roadmap.html", "rights", "The site's copyright section explicitly publishes the hosted transliteration tables under CC0; fonts have separate terms.", "CC0 applies to hosted transliterations. Other site materials and external originals retain their stated rights; no font is copied.", "verified_web"),
        ("zl3b", "Zandbergen-Landini transliteration, ZL3b", "René Zandbergen; Gabriel Landini acknowledged in source provenance", "https://voynich.nu/data/ZL3b-n.txt", "transcriptions", "Actual IVTFF 2.0 EVA source, version 3b dated 2025-05-13; retrieved bytes and uncertainty-preserving local copy are pinned.", "CC0 according to the host's explicit transliteration licensing statement. Preserve source header, comments and attribution.", "retrieved_and_hashed"),
        ("gc2a", "Glen Claston v101 transliteration, GC2a", "Glen Claston; IVTFF conversion hosted by René Zandbergen", "https://voynich.nu/data/GC2a-n.txt", "transcriptions", "Independent v101 reading, IVTFF 2a dated 2023-02-05, modified 2025-06-25; raw bytes retrieved for future alignment.", "CC0 according to host's explicit table license. Different alphabet prevents naïve character-by-character agreement scoring.", "retrieved_and_hashed"),
        ("takahashi-original", "Takeshi Takahashi original transcription pages", "Takeshi Takahashi", "https://www.voynich.com/pages/", "transcriptions", "A further independent EVA reading. Original site states conditions for saving and republication; this project records its existence only.", "Reference only: downloading/printing requires an email notice; republication requires permission. No notice or permission is claimed.", "verified_web_reference_only"),
        ("ivtff-2", "Intermediate Voynich Transliteration File Format 2.0", "René Zandbergen", "https://voynich.nu/software/ivtt/IVTFF_format.pdf", "specification", "Format reference for page/locus identities, continuations, alternate readings, uncertain spacing and page/text tags.", "PDF referenced, not mirrored. Parser implements a documented subset and retains original bytes.", "verified_web"),
        ("zandbergen-2022", "Transliteration of the Voynich MS Text", "René Zandbergen", "https://ceur-ws.org/Vol-3313/keynote1.pdf", "original_paper", "Original talk on representation choices and alignment of differing readings.", "CC BY 4.0 per proceedings. Original annotation only; no PDF mirrored.", "verified_web"),
        ("davis-2022", "Voynich Paleography", "Lisa Fagin Davis", "https://ceur-ws.org/Vol-3313/keynote2.pdf", "original_paper", "Paleographic talk entry verified in the proceedings; full PDF exceeded the browser document-size limit. IVTFF separately specifies the H-label convention.", "CC BY 4.0 per proceedings. Full talk not inspected in this seed pass; automated clusters do not verify paleographic identities.", "metadata_verified_fulltext_blocked"),
        ("dimperio-1978", "The Voynich Manuscript: An Elegant Enigma", "Mary E. D'Imperio", "https://www.nsa.gov/portals/75/documents/about/cryptologic-heritage/historical-figures-publications/publications/misc/voynich_manuscript.pdf", "historical", "1978 analytical monograph identified in Yale's catalog; browser retrieval of the NSA copy exceeded its 25 MB document limit.", "Bibliography verified through custodian catalog. Full PDF was not inspected or copied in this seed pass.", "metadata_verified_fulltext_blocked"),
        ("reddy-knight-2011", "What We Know About The Voynich Manuscript", "Sravana Reddy; Kevin Knight", "https://aclanthology.org/W11-1511/", "original_paper", "Analytical inventory and statistical questions useful for building explicit reproduction targets.", "Publisher record and linked paper inspected; metadata and original annotations only.", "verified_web"),
        ("lindemann-bowern-2020", "Character Entropy in Modern and Historical Texts", "Luke Lindemann; Claire Bowern", "https://arxiv.org/abs/2010.14697v2", "original_paper", "Studies conditional character predictability across alternative Voynich encodings and comparison corpora.", "Version 2, revised 2021-05-18. Our baseline uses a smaller declared comparison and does not reproduce the full paper.", "verified_web"),
        ("voynich-public-code", "Voynich-public companion research repository", "Yale Voynich Working Group; chirila repository maintainers", "https://github.com/chirila/Voynich-public", "code", "Companion code/corpus entry point for historical and multilingual comparison studies.", "No root redistribution license established in this pass; no source code or corpora imported.", "verified_web_reference_only"),
        ("montemurro-zanette-2013", "Keywords and Co-Occurrence Patterns in the Voynich Manuscript", "Marcelo A. Montemurro; Damián H. Zanette", "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066344", "original_paper", "Information-based word organization analysis, interpreted by its authors as evidence for linguistic structure.", "Publisher open-access record; original annotation only. Statistical organization alone does not assign semantics.", "verified_web"),
        ("sterneck-polish-bowern-2021", "Topic Modeling in the Voynich Manuscript", "Rachel Sterneck; Annie Polish; Claire Bowern", "https://arxiv.org/abs/2107.02858", "original_paper", "Compares computational topics with illustration and scribe categories, motivating confound-aware replication.", "Original annotation only. Our symbol-frequency clustering is not a replication of the paper's topic models.", "verified_web"),
        ("gaskell-bowern-2022", "Gibberish after all?", "Daniel Gaskell; Claire Bowern", "https://ceur-ws.org/Vol-3313/paper4.pdf", "original_paper", "Human-generated meaningless samples provide a competing explanation for some language-like text statistics.", "CC BY 4.0 per proceedings. Synthetic templates here do not substitute for the paper's human-produced sample set.", "verified_web"),
        ("bowern-gaskell-2022", "Enciphered after all?", "Claire Bowern; Daniel Gaskell", "https://ceur-ws.org/Vol-3313/paper6.pdf", "original_paper", "Investigates compatibility of word-level metrics with particular encipherment mechanisms.", "CC BY 4.0 per proceedings. Compatibility with selected metrics is weaker than identification of a cipher.", "verified_web"),
        ("timm-2015", "How the Voynich Manuscript was created", "Torsten Timm", "https://arxiv.org/abs/1407.6639v3", "original_paper", "Proposes a text-generation explanation based on similarly spelled words; it competes with linguistic interpretations.", "Version 3, 2015-12-09. Treat mechanism identification as the author's hypothesis, not a settled conclusion.", "verified_web"),
        ("voy2022", "International Conference on the Voynich Manuscript 2022 proceedings", "Colin Layfield; John Abela, editors", "https://ceur-ws.org/Vol-3313/", "proceedings", "Verified program and paper metadata covering paleography, history, cryptography and quantitative analysis.", "Papers CC BY 4.0; proceedings bibliography CC0. Catalog is selective, not an exhaustive literature review.", "verified_web"),
        ("alice-english", "Alice's Adventures in Wonderland, Project Gutenberg eBook 11", "Lewis Carroll; e-text credits Arthur DiBianca and David Widger", "https://www.gutenberg.org/ebooks/11", "comparison_corpus", "Meaningful English prose comparison with pinned complete text, body delimiters and lowercase a-z normalization.", "Public domain in the USA per item record. Preserve full Gutenberg notice in the redistributed source; users elsewhere check local terms.", "retrieved_and_hashed"),
        ("dioscorides-comparator", "Of Medical Substances: Dioscurides Neapolitanus", "Biblioteca Nazionale di Napoli; Library of Congress / World Digital Library record", "https://www.loc.gov/resource/gdcwdl.wdl_10690/?sp=9&st=gallery", "historical_comparator", "Historically relevant herbal illustration comparator located in the custodian catalog; automated object retrieval returned 403.", "Reference only. Image rights, full metadata and an aligned machine-readable text remain acquisition tasks.", "metadata_located_access_blocked"),
    ]
    records = []
    for sid, title, authors, url, category, summary, rights, status in sources:
        records.append({"id": sid, "title": title, "authors": authors, "canonical_url": url, "url": url, "category": category, "summary": summary, "rights": rights, "rights_status": "source_specific", "retrieval_status": status, "status": status, "verified_at": DATE, "verification_method": "Primary source browser inspection; downloaded artifacts additionally hashed in data/manifests. Failed access is explicitly recorded.", "seed": True, "competitive_points": 0})
    save("sources/catalog.json", records)
    for name, sid, attribution in [("ZL3b-n.txt", "zl3b", "René Zandbergen; Gabriel Landini"), ("GC2a-n.txt", "gc2a", "Glen Claston; IVTFF conversion René Zandbergen"), ("pg11.txt", "alice-english", "Lewis Carroll; Project Gutenberg; Arthur DiBianca; David Widger")]:
        raw = ROOT / "data/raw" / name
        target = ROOT / "data/corpora" / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(raw.read_bytes())
        is_pg = name == "pg11.txt"
        save(f"data/manifests/{sid}.json", {"schema_version": "1.0", "id": sid, "path": f"data/corpora/{name}", "origin": "https://www.gutenberg.org/cache/epub/11/pg11.txt" if is_pg else f"https://voynich.nu/data/{name}", "sha256": hashlib.sha256(raw.read_bytes()).hexdigest(), "byte_length": raw.stat().st_size, "media_type": "text/plain", "source_id": sid, "rights": "Public domain in USA; complete Gutenberg source notice retained; see source record for territorial limits." if is_pg else "CC0-1.0; explicit hosted-transliteration terms https://voynich.nu/roadmap.html, verified 2026-09-06. Original attribution retained.", "redistribution": "permitted", "state": "verified", "attribution": attribution, "retention": "Versioned immutable research source; corrections are new versions, not silent normalization."})
    save("data/transcriptions/catalog.json", [
        {"id": "transcription-zl3b", "title": "ZL3b", "producer": "René Zandbergen, from the EVMT/LZ project with Gabriel Landini", "version": "3b, 2025-05-13", "alphabet": "Extended EVA", "format": "IVTFF 2.0", "source_id": "zl3b", "retrieval": "retrieved, full bytes hashed and distributed under hosted CC0 terms", "manifest": "data/manifests/zl3b.json", "independence": "A reading distinct from Glen Claston's v101 effort, with later corrections; shared source manuscript is not independent data.", "limitations": ["Comments include speculative historical and botanical identifications.", "No full image-based accuracy audit has yet occurred."]},
        {"id": "transcription-gc2a", "title": "GC2a", "producer": "Glen Claston; IVTFF conversion René Zandbergen", "version": "2a, 2023-02-05, modified 2025-06-25", "alphabet": "v101", "format": "IVTFF 2.0", "source_id": "gc2a", "retrieval": "retrieved, full bytes hashed and distributed under hosted CC0 terms", "manifest": "data/manifests/gc2a.json", "independence": "Independently produced glyph reading/alphabet relative to ZL; converted locus metadata may be shared.", "limitations": ["Baseline EVA normalization deliberately does not process v101 characters.", "Alphabet conversion and locus alignment need independent validation before disagreement metrics are reported."]},
        {"id": "transcription-tt", "title": "Takahashi original pages", "producer": "Takeshi Takahashi", "version": "Original website; per-page versions not pinned", "alphabet": "EVA", "format": "HTML pages", "source_id": "takahashi-original", "retrieval": "reference_only; no download/printing notice sent", "rights": "Original site download and reproduction terms differ from the CC0 statement on converted hosted copies; resolve scope before copying.", "independence": "Further independently produced reading; not a new reading when copied into LSI or IT."},
    ])
    branches = [
        ("corpus-integrity", "Corpus integrity and uncertainty", "Which uncertainty and segmentation choices change downstream conclusions?", ["method-parse", "method-agreement"], [], "Align a documented sample of ZL and GC loci before calculating disagreement."),
        ("layout-paleography", "Codicology, paleography and layout", "Which text differences survive controls for page layout, quire and source-specific hand labels?", ["method-stratification", "method-agreement"], ["corpus-integrity"], "Verify a blinded set of page/hand labels against cited loci and preserve disagreement."),
        ("statistical-structure", "Statistical structure", "Which distributional and positional effects differ from declared matched controls?", ["method-frequency", "method-entropy", "method-position"], ["corpus-integrity"], "Reproduce all three normalization variants of the five local baselines."),
        ("morphology-segmentation", "Morphology and segmentation", "What structure persists when apparent spaces and glyph units are varied?", ["method-segmentation", "method-ngram"], ["corpus-integrity", "statistical-structure"], "Freeze two segmentation models and test held-out pages with equal search budgets."),
        ("generative-mechanisms", "Cryptographic and generative mechanisms", "Which bounded cipher or pseudotext families jointly predict held-out diagnostics?", ["method-cipher", "method-generative"], ["statistical-structure"], "Specify a finite generator family and complexity cost before fitting it."),
        ("semantic-multimodal", "Semantic and multimodal constraints", "Do text-image associations survive blinded annotation and shuffled associations?", ["method-cluster", "method-multimodal"], ["layout-paleography", "statistical-structure"], "Construct a small consented, rights-cleared annotation panel with competing labels."),
        ("historical-comparanda", "Historical comparanda and provenance", "Which dated textual, visual and cipher practices impose useful constraints?", ["method-history", "method-cipher"], [], "Resolve source rights and locate a machine-readable historical herbal comparator."),
        ("replication-decipherments", "Replication and candidate decipherments", "Can a fully specified procedure make predeclared predictions on unseen manuscript material?", ["method-replication", "method-cipher"], ["corpus-integrity", "statistical-structure"], "Select one published procedure and produce a step-by-step evidence and failure checklist."),
    ]
    for bid, title, question, methods, deps, first in branches:
        save(f"research/branches/{bid}.json", {"id": bid, "title": title, "summary": question, "question": question, "status": "open", "methods": methods, "dependencies": deps, "depends_on": deps, "next_step": first, "first_experiment": first, "seed": True, "competitive_points": 0})
    method_rows = [
        ("parse", "Uncertainty-preserving corpus parsing", "corpus-integrity", "Count format violations, alternative readings and token exclusions under explicit policies.", "Locus IDs and alphabet metadata are correctly interpreted.", "Synthetic malformed and foldout fixtures; raw byte hashes; alternative-space variants.", "Cannot decide which reading is correct or identify language units.", "ivtff-2"),
        ("agreement", "Independent annotation and reading agreement", "corpus-integrity", "Align named loci and report agreement with uncertainty and adjudication history.", "Annotators follow a shared protocol; reading lineages are recorded.", "Blinded duplicate annotation; chance and prevalence checks; disagreements retained.", "Agreement is not accuracy; converted copies of one reading are not independent witnesses.", "davis-2022"),
        ("stratification", "Codicological stratification", "layout-paleography", "Partition effects by source-specific quire, layout, section and hand labels.", "Label provenance and unit boundaries are known.", "Within-quire permutations; leave-one-quire-out checks; mixed labels excluded or modeled.", "Labels and neighboring foldouts are confounded; a partition does not establish a scribe.", "yale-catalog"),
        ("frequency", "Frequency and encoded token lengths", "statistical-structure", "Report counts, rank distributions, hapax types and token-length histograms.", "Token/character conventions are declared and stable.", "Matched text lengths, shuffled characters and meaningful prose; sensitivity to spaces.", "Zipf-like curves and length fits cannot identify meaning or a specific language.", "reddy-knight-2011"),
        ("entropy", "Conditional entropy diagnostics", "statistical-structure", "Estimate empirical next-symbol uncertainty under declared token/boundary conventions.", "Encoded units, sample boundaries and estimator are fixed.", "Equal symbol count; boundary and glyph-composition variants; known plaintext and shuffled nulls.", "Finite-sample bias, script differences and genre remain; low entropy is not a decipherment.", "lindemann-bowern-2020"),
        ("ngram", "Held-out sequence models", "morphology-segmentation", "Fit finite n-gram models and report held-out cross-entropy and parameter count.", "Training and test partitions are separated before fitting.", "Equal tuning budgets; simpler baselines; out-of-quire evaluation.", "Predictive fit does not identify a production mechanism; related pages can leak information.", "reddy-knight-2011"),
        ("segmentation", "Morphology and segmentation sensitivity", "morphology-segmentation", "Compare limited boundary and affix hypotheses using held-out compression or predictions.", "Apparent manuscript spaces need not be lexical boundaries.", "Character-shuffled controls; equal model complexity; report all tested segmentations.", "A useful encoding can compress pseudotext; affixes need not encode grammar.", "bowern-gaskell-2022"),
        ("position", "Line position and local repetition", "statistical-structure", "Measure first/last-token length and repeated adjacent-token rates by locus type.", "Locus-to-line mapping and exclusions are explicit.", "Within-line shuffles preserving token multiset; uncertainty sensitivity; source checks.", "Discarded uncertain words can create apparent adjacency; layout conventions can mimic grammar.", "reddy-knight-2011"),
        ("cluster", "Clustering and topic-model auditing", "semantic-multimodal", "Compare text-derived groups to source-specific labels with permutation diagnostics.", "Features, k, initialization and preprocessing are declared before evaluation.", "Label permutations within quire; equal page-length controls; held-out assignment.", "Association is not semantics. Scribe, section, quire and page length can confound each other.", "sterneck-polish-bowern-2021"),
        ("cipher", "Bounded cipher-family testing", "generative-mechanisms", "Specify reversible procedures and test predeclared held-out predictions and failure conditions.", "Keys, substitutions, exceptions and search domain are fully disclosed.", "Known-plaintext recovery; decoy languages; equal search budget and exception penalties.", "Flexible readings and unconstrained anagrams can fit almost anything; historical plausibility needs separate evidence.", "bowern-gaskell-2022"),
        ("generative", "Pseudotext and mechanism controls", "generative-mechanisms", "Fit finite generators and compare several held-out diagnostics, not a selected resemblance.", "Generator family, seed scope and parameter budget are frozen.", "Known-language, character-shuffle, copy/mutate and grammar controls; all attempts retained.", "Matching measured statistics does not prove this generator produced the manuscript.", "timm-2015"),
        ("history", "Historical constraint and provenance testing", "historical-comparanda", "Trace dated ownership, material and textual claims to inspectable primary evidence.", "Dating methods and source chains have explicit uncertainties.", "Competing chronologies; distinguish material date from writing date; named counterevidence.", "Catalogs can repeat obsolete assertions; stylistic resemblance alone does not establish origin.", "yale-catalog"),
        ("multimodal", "Blinded image-text association", "semantic-multimodal", "Test proposed associations against independently labeled images and randomized pairing.", "Rights-cleared images and non-leading annotation criteria are available.", "Blinded annotators; decoy images; withheld folios; competing plant identifications.", "Resemblance is subjective; pictures and text could be only loosely related.", "montemurro-zanette-2013"),
        ("replication", "Explicit replication and falsification", "replication-decipherments", "Reconstruct a published procedure, inspect input availability and record exact departures.", "Target claim, implementation lineage and acceptance criterion are fixed.", "Independent implementation where possible; retained failures; code and data hashes.", "A same-author rerun is reproducibility checking, not independent human validation.", "gaskell-bowern-2022"),
    ]
    for mid, title, branch, summary, assumptions, controls, limits, source in method_rows:
        save(f"methods/{mid}.json", {"id": f"method-{mid}", "title": title, "summary": summary, "branch_ids": [branch], "assumptions": [assumptions], "controls": [controls], "limitations": [limits], "sources": [source], "cost": "CPU-scale initial protocol or small manual evidence audit; declare exact budget before expanding.", "status": "available_method_card", "seed": True, "competitive_points": 0})
    tasks = [
        ("01-source-rights", "Verify one source's reuse and version record", "historical-comparanda", "novice", "Inspect an official source, record exact item/version/rights evidence and correct a material catalog defect if found.", "Source metadata and a concrete before/after correction with quoted locator; link-only additions do not suffice.", 2),
        ("02-align-readings", "Align a bounded ZL/GC sample", "corpus-integrity", "intermediate", "Choose 20 predeclared loci across two illustration categories; document alphabet conversion and uncertain matches.", "Alignment table, excluded loci, reversible mapping, checks and uncertainty report.", 5),
        ("03-foldout-index", "Check foldout and missing-leaf indexing", "layout-paleography", "novice", "Verify f85/f86 panel conventions and three named missing leaves against custodian and format sources.", "Cited corrections separating leaves, sides, panels, loci and scans; no invented canvas IDs.", 2),
        ("04-parser-audit", "Audit uncertainty parser edge cases", "corpus-integrity", "intermediate", "Independently inspect literal IVTFF uncertainty, tags and drawing interruptions against the specification.", "Demonstrated behavior defect and useful fix, or substantive audit with retained checks.", 5),
        ("05-entropy-sensitivity", "Reproduce entropy and space-policy baselines", "statistical-structure", "novice", "Run the documented offline three-variant loop; compare all controls and investigate a material discrepancy.", "A routine matching rerun is service at tier 0; a documented new informative defect can meet tier 2 or a substantive replication tier 10.", 0),
        ("06-length-matching", "Check sample-length bias in frequency metrics", "statistical-structure", "intermediate", "Predeclare equal-length windows and inspect whether type-token differences remain stable across them.", "All windows/attempts, matched controls, uncertainty and no selected-best language.", 5),
        ("07-line-map", "Validate a locus-to-physical-line sample", "layout-paleography", "intermediate", "Map 30 declared P0/Pt loci to actual image lines when official images are accessible.", "Rights/canvas provenance, annotation criteria and retained disagreements.", 5),
        ("08-segmentation-protocol", "Propose a bounded segmentation comparison", "morphology-segmentation", "intermediate", "Specify two competing boundary models and a disjoint held-out folio partition.", "Executable protocol, complexity penalty, nulls, failure criteria and finite search scope.", 5),
        ("09-generator-controls", "Test one finite pseudotext family", "generative-mechanisms", "advanced", "Freeze a generator, parameter grid and joint metrics before testing held-out pages.", "All parameter runs, known plaintext recovery, uncertainty and explicit excluded overlap with seed null.", 10),
        ("10-cipher-benchmark", "Build a known-plaintext cipher diagnostic", "generative-mechanisms", "intermediate", "Choose a historically documented reversible transform and verify recovery on authored plaintext.", "Source, key/exception budget, decoys, correctness tests and worked output.", 5),
        ("11-hand-confounds", "Audit section-hand-quire confounding", "layout-paleography", "advanced", "Use ZL labels as sourced hypotheses and quantify overlap before any hand classification claim.", "Contingency tables, mixed-label handling, constrained permutations and source-limited conclusions.", 5),
        ("12-blind-image-protocol", "Design a blinded image-label pilot", "semantic-multimodal", "intermediate", "Describe candidate/decoy labels and a rights-cleared folio sample without inspecting test associations.", "Protocol and consent/rights plan; no fabricated annotator results.", 5),
        ("13-historical-corpus", "Acquire a historical herbal comparison text", "historical-comparanda", "intermediate", "Find a custodian-backed readable text and establish item-level redistribution terms.", "Usable pinned source, normalization documentation and actual matched baseline run.", 5),
        ("14-replicate-entropy", "Extend the partial entropy replication", "replication-decipherments", "advanced", "Recover the paper's declared encodings and comparison subset; log departures from the original setup.", "Actual independent implementation/data inspection and complete or informative partial report.", 10),
        ("15-replicate-topics", "Reconstruct one topic-model experiment", "replication-decipherments", "advanced", "Select a specific paper table/model and recover its inputs, labels and preprocessing.", "Pinned implementation, declared comparison tolerance and actual execution or informative failure.", 10),
        ("16-unique-direction", "Suggest a useful distinct research direction", "replication-decipherments", "novice", "State a concrete question, research rationale, bounded prior-work search and plausible first step.", "A distinct useful suggestion can meet tier 2 before a full protocol or experiment; vague or repeated suggestions meet 0.", 2),
        ("17-source-chronology", "Check one historical attribution chain", "historical-comparanda", "novice", "Distinguish a legacy catalog assertion from later primary evidence for one ownership/dating claim.", "Traceable chain, dated sources, uncertainty and concrete consequence for research choices.", 2),
        ("18-instrument-accessibility", "Improve access to a research instrument", "statistical-structure", "intermediate", "Identify a demonstrated accessibility or reproducibility barrier in the worked analysis flow and repair it.", "Before/after evidence and a usable example; generic cosmetic activity remains tier 0.", 5),
    ]
    for tid, title, branch, level, summary, evidence, tier in tasks:
        save(f"research/first-tasks/task-{tid}.json", {"id": f"task-{tid}", "title": title, "summary": summary, "branch_ids": [branch], "difficulty": level, "status": "open", "acceptance_evidence": evidence, "tier_anchor": tier, "scoring_note": "Indicative evidence anchor only. Mission gates, family overlap and prior seed baselines govern any AI assessment; tasks reserve neither ownership nor points.", "seed": True, "competitive_points": 0})
    claims = [
        ("representation", "EVA units are not recovered language letters", "EVA encodes visible shapes; composed sequences should not automatically be interpreted as linguistic characters.", "zandbergen-transliterations", "corpus-integrity", "source_supported_methodological_constraint", "Compare alternate glyph composition conventions before interpreting entropy or lengths."),
        ("uncertain-spaces", "Spacing uncertainty can alter token statistics", "ZL explicitly records ambiguous spaces and alternative readings; derived token counts depend on their treatment.", "zl3b", "corpus-integrity", "under_test", "Compare fixed join, split and strict variants, retaining every exclusion."),
        ("entropy-structure", "Voynich conditional character predictability is unusual in published comparisons", "Lindemann and Bowern report low conditional entropy across their encodings and corpus comparisons.", "lindemann-bowern-2020", "statistical-structure", "reported_not_independently_replicated_here", "Recover original corpora and estimator conventions; current baseline is a scoped partial reconstruction."),
        ("topic-labels", "Text-derived clusters can associate with source labels", "Sterneck and colleagues report topic groups associated with illustration and scribal categories.", "sterneck-polish-bowern-2021", "semantic-multimodal", "reported_not_independently_replicated_here", "Replicate the models and test label permutations within quire/hand; association alone does not assign meanings."),
        ("meaningful-organization", "Statistical organization may constrain explanations", "Montemurro and Zanette interpret measured word organization as supporting a linguistic account.", "montemurro-zanette-2013", "statistical-structure", "competing_interpretation", "Test the same diagnostics against predeclared structured pseudotext families."),
        ("meaningless-controls", "Human meaningless text can share selected statistics", "Gaskell and Bowern compare Voynich metrics with human-produced meaningless samples.", "gaskell-bowern-2022", "generative-mechanisms", "competing_interpretation", "Acquire original sample-level outputs and examine sampling and feature-selection limits."),
        ("encipherment-compatible", "Some encipherment remains compatible with word-level metrics", "Bowern and Gaskell investigate cipher mechanisms whose outputs preserve relevant word-level statistics.", "bowern-gaskell-2022", "generative-mechanisms", "bounded_compatibility_claim", "Implement named transforms with known plaintext, equal parameter budgets and held-out tests."),
        ("copy-generation", "Copy-related generation is a candidate explanation", "Timm proposes a mechanism involving similarly written words; this competes with interpretations requiring recoverable linguistic meaning.", "timm-2015", "generative-mechanisms", "hypothesis_untested_here", "Reconstruct the exact proposed algorithm and compare joint held-out metrics; the seed null is not that algorithm."),
        ("hand-variation", "Scribal variation is a paleographic research hypothesis", "Davis provides paleographic analysis that informs the source's H labels.", "davis-2022", "layout-paleography", "source_specific_annotation", "Inspect glyph evidence independently and distinguish Davis H labels from Currier C labels."),
        ("catalog-dating", "Legacy catalog dating and ownership assertions need source dating", "The older Yale description contains claims that should be examined alongside more recent custodian evidence.", "yale-catalog", "historical-comparanda", "historical_source_audit_needed", "Trace one named attribution or chronology to dated primary evidence; do not copy it as settled fact."),
        ("folio-units", "Physical leaves, page units and scans are distinct", "Yale's physical-leaf count and IVTFF foldout-locus conventions describe different units.", "ivtff-2", "layout-paleography", "source_supported_methodological_constraint", "Verify fRos and panel conventions against actual custodian images when accessible."),
        ("no-solution", "A decipherment must make constrained unseen predictions", "A proposed solution needs a specified procedure and held-out evidence beyond matching a few selected words or illustrations.", "reddy-knight-2011", "replication-decipherments", "project_methodological_requirement", "Use research/solution-protocol.md; keep failures and exception budgets visible."),
    ]
    for cid, title, summary, source, branch, state, test in claims:
        save(f"research/claims/{cid}.json", {"id": f"claim-{cid}", "title": title, "summary": summary, "statement": summary, "sources": [source], "branch_ids": [branch], "status": state, "epistemic_status": state, "test_or_next_step": test, "limitations": ["Source reporting is distinguished from project execution and independent validation; no universal truth or full translation is asserted."], "seed": True, "competitive_points": 0})
    directions = [
        ("uncertainty-ranking", "Rank research conclusions by uncertainty sensitivity", "corpus-integrity", "Which claimed effects change most when uncertain reading and spacing policies are varied?", "A sensitivity ranking could prioritize the image loci whose reinspection would most improve confidence.", "Combines available alternative-reading annotations with effects already present in the baseline, rather than simply requesting another transcription.", ["zl3b", "lindemann-bowern-2020"], "Calculate effect ranges for the three frozen baseline variants and identify the responsible locus set."),
        ("negative-control-atlas", "Create a diagnostic failure atlas for candidate mechanisms", "generative-mechanisms", "Which deliberately wrong generators pass individual metrics while failing joint held-out tests?", "Exposing easy false positives can prevent promising-looking but weak decipherment claims from dominating effort.", "Focus is failure characterization across a finite declared control set; it does not claim novelty for copy/mutate generation itself.", ["timm-2015", "gaskell-bowern-2022", "bowern-gaskell-2022"], "Write a small table of three fixed mechanisms and predeclare two held-out diagnostics before execution."),
        ("confound-information", "Measure what additional annotation would resolve section-hand confounding", "layout-paleography", "Which underrepresented combinations of section and source-specific hand labels would best distinguish competing explanations?", "A map of missing combinations can direct limited manual annotation to useful evidence instead of collecting more of the same examples.", "An annotation-priority proposal, separate from re-running a cluster algorithm or treating its labels as truth.", ["davis-2022", "sterneck-polish-bowern-2021"], "Audit the existing label contingency table and list a bounded image sample with an explicit sampling rationale."),
        ("decipherment-budget", "Record the flexibility budget of a proposed decipherment", "replication-decipherments", "How many optional readings, exceptions and selection choices are needed before a proposed procedure matches its examples?", "A visible flexibility budget turns a vague dispute into inspectable assumptions and testable out-of-sample predictions.", "Operationalizes an audit of a particular complete procedure; it is not a generic request to use AI or try a new language.", ["reddy-knight-2011", "bowern-gaskell-2022"], "Choose one publicly specified procedure and tabulate every discretionary choice on a fixed passage."),
    ]
    for did, title, branch, question, rationale, distinct, refs, first in directions:
        save(f"research/directions/{did}.json", {"schema_version": "1.0", "id": f"direction-{did}", "title": title, "question": question, "rationale": rationale, "distinctness": distinct, "prior_work_check": {"scope": "Bounded launch-source catalog and current seed directions inspected; this does not establish world-first novelty.", "references": refs, "checked_at": DATE}, "first_step": first, "limitations": ["Candidate suggestion only; detailed protocol and execution are future work.", "Designated seed: zero competitive allocations; evidence-tier baseline awaits official assessment."], "attribution": ["voynich.win launch curation, AI-assisted by OpenAI Codex; exposed precise model version not recorded"], "branch_ids": [branch], "family_id": f"seed-direction-{did}", "status": "candidate"})
    save("research/seed-families.json", [
        {"id": "seed-source-catalog", "scope": "This curated bounded source inventory and rights/provenance records.", "acceptance_test": "Inspect source-level provenance, original annotations and explicit failed retrievals."},
        {"id": "seed-corpus-parser", "scope": "Pinned ZL/GC corpora, folio/locus metadata and tested EVA uncertainty parser.", "acceptance_test": "Verify source hashes, rights, parser invariants and normalization disclosures."},
        {"id": "seed-research-navigation", "scope": "Eight initial branches, fourteen method cards, twelve claims and eighteen bounded tasks.", "acceptance_test": "Inspect each record's actionable question, source, limitations and overlapping scope."},
        {"id": "seed-local-harness", "scope": "CPU-only frozen-protocol prepare/run/compare/bundle workflow with all attempts and controls.", "acceptance_test": "Execute the offline worked example and verify the complete bundle."},
        *[{"id": f"seed-baseline-{key}", "scope": scope, "acceptance_test": "Reproduce actual versioned output under all three declared variants and inspect controls and limits."} for key,scope in [("integrity", "Coverage and normalization audit of pinned ZL3b."), ("frequency", "Encoded frequency and length diagnostics with matched controls."), ("entropy", "Conditional symbol entropy under explicit encoding/boundary conventions."), ("position", "P0 locus position/repetition and within-locus shuffle diagnostics."), ("clustering", "Encoded-symbol clustering with source-specific section/hand/quire confound diagnostics.")]],
        *[{"id": f"seed-direction-{row[0]}", "scope": row[1], "acceptance_test": "Inspect suggestion usefulness, bounded prior-work check, distinction and plausible first step."} for row in directions],
    ])
    print(json.dumps({"sources": len(records), "verified_or_retrieved_sources": sum(x["status"].startswith(("verified", "retrieved")) for x in records), "branches": len(branches), "methods": len(method_rows), "tasks": len(tasks), "claims": len(claims), "directions": len(directions)}))


if __name__ == "__main__":
    main()
