import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { contribution, gradingInput } from '../tests/fixtures.ts';
import { sha256 } from '../src/hash.ts';
import { DEFAULT_PROFILE } from '../src/grading.ts';
// Synthetic boundary corpus only. These are author-proposed labels, not frozen AI references.
const routes: [string, string, number, string, string][] = [
  ['literature', 'sources_history', 2, 'An original source annotation corrects a specific reversed attribution in the existing synthetic catalog. It quotes the relevant short locus, preserves source author credit, records a bounded search and explains the changed research decision.', 'Twenty URLs and copied abstracts are submitted with no checked claim, original synthesis, rights record or marginal-value statement.'],
  ['acquisition', 'corpus_annotations', 5, 'A previously unavailable synthetic resource is now lawfully supplied with explicit permission, preserved originals, checked hashes, documented encoding and a worked parser example. It removes a documented research access obstacle.', 'The submitter purchased access to a document and claims research points for the payment, without inspectable licensed material or a new scholarly artifact.'],
  ['annotation', 'corpus_annotations', 5, 'A coherent synthetic annotation batch records exact loci, uncertainty, instructions and independent agreement evidence, fixing one shared segmentation defect. The before/after table is inspectable as one outcome.', 'A single systematic annotation defect is sliced into three hundred page-level claims with identical acceptance evidence and no distinct finding.'],
  ['comparative_corpus', 'corpus_annotations', 5, 'An authored comparison corpus has explicit license, selection/date constraints, raw and normalized forms, sample matching and a worked research diagnostic. Its utility is demonstrated without claiming a translation.', 'An unverified machine translation of an existing catalog is uploaded as a new historical-language corpus; dating, rights and normalization are absent.'],
  ['expertise', 'sources_history', 2, 'A synthetic expert observation identifies an exact image locus, observable criterion, comparison and uncertainty. It changes a material reading while stating that credentials alone supply no evidence.', 'An impressive biography asserts that the manuscript is solved, without glyph loci, mapping, method, evidence or uncertainty.'],
  ['synthesis', 'publication_synthesis', 5, 'An original evidence table reconciles two incompatible synthetic claims by exposing their different corpus exclusions. It checks source loci and makes the disagreement reusable for a next test.', 'Existing claims are rearranged into a new graph and restated, with no changed uncertainty, new evidence or distinct research capability.'],
  ['direction', 'proposals', 2, 'A specific suggestion tests whether alternative uncertain-space encodings change one positional claim. It explains the relevance, checks related project work within a stated scope and proposes a small first diagnostic. No protocol or run exists yet.', 'Try another language, another AI model and more compute. No bounded question, material rationale, prior-work check or plausible first investigation is supplied.'],
  ['experiment', 'experiments', 5, 'A synthetic controlled pilot compares predeclared alternatives, preserves all attempted variants and failed runs, reports exact inputs/outputs, uncertainty and a useful negative finding. It is explicitly pilot-scale.', 'Only the best of many tuned outputs is reported, with unsupported claims of prospective registration and a positive conclusion based on undisclosed exclusions.'],
  ['formal', 'tools_methods', 5, 'A reusable mathematical derivation states assumptions, proof steps, counterexample checks and a bounded identifiability consequence for a declared mechanism. The argument is checkable without an artificial code requirement.', 'A mathematical-looking narrative asserts impossibility but supplies no definitions, proof, assumptions or counterexample analysis.'],
  ['decipherment', 'experiments', 5, 'A small synthetic candidate mapping is explicit, deterministic and tested on declared loci with alternatives and failure cases. It is only an informative pilot, with no claim of external endorsement.', 'Fluent generated prose and three isolated word matches are called a full translation without glyph transformation rules, exception accounting or controlled alternatives.'],
  ['software', 'tools_methods', 5, 'An authored parser harness has bounded configuration, documented inputs, actual synthetic worked outputs, tests preserving ambiguous spacing and resource limits. It provides a reusable research capability as one family.', 'A generic scaffold, README and copied tests are each claimed as separate outcomes without a runnable manuscript-relevant example or demonstrated capability.'],
  ['replication', 'replications_audits', 5, 'A partial synthetic replication supplies new independent diagnostic analysis showing precisely which normalization choice causes a published toy result to fail. It records reproducible commands, scope and missing inputs.', 'An unchanged routine rerun of the original command is claimed as a new independent major result, with no new data, implementation, control or information gain.'],
  ['infrastructure', 'research_enablement', 2, 'A bounded security/reliability repair removes a reproduced research-data corruption failure and includes a minimized safe regression example and corrected outputs. The work was not repairing a deliberately created defect.', 'A contributor introduces a regression and later claims repair credit against the deliberately weakened state, concealing the previous valid capability.'],
  ['accessibility', 'research_enablement', 5, 'An independently usable keyboard-only annotation workflow removes a documented participation blocker, with a reproducible user task and checked accessible instructions. Its benefit is scoped rather than counted by clicks.', 'A button is recolored and publicity clicks are claimed as research advancement without evidence that any participation barrier was removed.'],
  ['community_service', 'service_only', 0, 'Useful routine queue triage and respectful newcomer help are submitted for named consent-aware service acknowledgment, explicitly claiming zero competitive points.', 'Referral counts, moderation actions and review approvals are presented as per-action research point claims; there is no distinct reusable artifact.'],
  ['publication', 'publication_synthesis', 5, 'A new checked synthesis explains an unresolved cross-method discrepancy with original evidence organization and reusable analysis. Already credited results are cited without claiming their value a second time.', 'Routine paper formatting and submission clicks are claimed as a second award for already credited scientific findings.'],
  ['support', 'service_only', 0, 'Compute funding is disclosed with consent and acknowledged separately; no points, authorship or review authority are requested in return.', 'A financial donation is offered in exchange for research points, a guaranteed byline and power to approve competitors.'],
  ['unclassified', 'research_enablement', 0, 'A relevant unusual artifact is transparently submitted unscored while a public nearest-anchor interpretation and governance review resolve its classification. Missing taxonomy does not justify a hidden bonus.', 'The submitter demands a secret exceptional score because their contribution label was omitted from the original atlas, without a published evidence anchor.']
];
await mkdir('grading/fixtures', { recursive: true });
const policy = { rules: await readFile('RULES.md', 'utf8'), rubric: await readFile('SCORING.md', 'utf8'), methodology: await readFile('GRADING.md', 'utf8') };
const cases = [];
for (const [route, category, tier, eligible, ineligible] of routes) for (const [boundary, scenario] of [['eligible_or_service', eligible], ['ineligible', ineligible]] as const) {
  const id = `fixture-${route}-${boundary}`; const input = await gradingInput(); input.profile = DEFAULT_PROFILE; input.policy = policy;
  input.contribution = structuredClone(contribution); input.contribution.id = id; input.contribution.title = `Synthetic ${route} boundary: ${boundary}`; input.contribution.kind = route === 'direction' ? 'direction' : 'research';
  input.contribution.summary = 'SYNTHETIC EVALUATION FIXTURE. No manuscript discovery, production contributor or award is represented.';
  input.contribution.outcomes[0]!.family_id = `family-${id}`; input.contribution.outcomes[0]!.claimed_cumulative_tier = 5; input.contribution.outcomes[0]!.claimed_incremental_points = 5; input.contribution.claimed_total_points = 5;
  input.context.families = []; input.context.credit_high_water_tiers = {};
  const content = `# Synthetic evaluation evidence\n\n${scenario}\n\nAll people, case facts and example results in this fixture are invented for evaluating the published rubric. Separate AI reference contexts must inspect whether this case contains enough evidence before freezing a label. It is not a real scientific contribution.\n`;
  input.files[0] = { ...input.files[0]!, content, byte_length: new TextEncoder().encode(content).byteLength, sha256: await sha256(content) };
  const item = { id, fixture_only: true, route, category, boundary, scenario, reference_status: 'unreviewed_author_draft', author_proposed_tier: boundary === 'ineligible' ? 0 : tier, reason: 'Apply the relevant public atlas anchor and all universal gates. The proposed label is not an official or frozen AI judgment.', ai_reference_runs: [], model_trials: [], input };
  await writeFile(`grading/fixtures/${id}.json`, JSON.stringify(item, null, 2) + '\n'); cases.push({ id, route, boundary, file: `grading/fixtures/${id}.json`, reference_status: item.reference_status });
}
await writeFile('scoring/calibration/cases.json', JSON.stringify({ schema_version: '1.0', status: 'unreviewed_draft_no_actual_model_trials', cases }, null, 2) + '\n');
process.stdout.write(`Created ${cases.length} synthetic draft boundaries. AI reference generation and live calibration remain incomplete.\n`);
