import { readFile, writeFile } from 'node:fs/promises';
import { CATEGORIES } from '../src/contracts.ts';
const rules = await readFile('RULES.md', 'utf8');
const headings = [...rules.matchAll(/\*\*(R[1-8])\s+[—–-]\s+([^*]+)\*\*/g)];
const records = headings.map((match, index) => ({ id: match[1], title: match[2]!.trim(), text: rules.slice(match.index! + match[0].length, headings[index + 1]?.index ?? rules.indexOf('**How the rules are enforced**')).trim() }));
if (records.length !== 8) throw new Error('All eight normative global rules must export.');
await writeFile('governance/global-rules.yaml', JSON.stringify({ schema_version: '1.0', version: '0.1', status: 'founding_prelaunch_policy', rules: records }, null, 2) + '\n');
const rubric = { schema_version: '1.0', version: '0.1', status: 'provisional_uncalibrated', scoring_unit: 'independently useful marginal outcome family', categories: CATEGORIES,
  gates: [ ['G1', 'Mission-linked research question, direction or necessary shared capability.'], ['G2', 'Traceable inputs and acceptable rights/provenance.'], ['G3', 'Inspectable type-appropriate evidence; actual execution where claimed.'], ['G4', 'Explicit scope, assumptions, uncertainty, contrary evidence and limits.'], ['G5', 'Required human attribution and honest AI disclosure.'], ['G6', 'Incremental value after related-work, family overlap and seed review.'], ['G7', 'No fabricated evidence, concealed material selection or unsupported factual claims.'] ].map(([id, requirement]) => ({ id, requirement })),
  tiers: [ { points: 0, anchor: 'Acknowledged activity, duplicate, unsupported or service-only work; useful zero-point material may still merge.' }, { points: 2, anchor: 'Bounded verified improvement or distinct useful direction with rationale, bounded prior-work check and plausible first step; no full protocol or execution required for a direction.' }, { points: 5, anchor: 'Completed coherent reusable source synthesis, corpus batch, usable protocol/tool or informative pilot.' }, { points: 10, anchor: 'Controlled reproducible discriminating result, substantive independent replication or material corpus/method improvement with appropriate baselines and independent inspection/execution.' }, { points: 20, anchor: 'Independently validated major constraint/capability, with genuine nonconflicted external domain assessment.' } ],
  arithmetic: { units_per_point: 10000, attribution_basis_points: 10000, progression: 'max(0, assessed_tier - current_credit_high_water_tier)', family_maximum: 20, seed_allocation: 0, corrections_reopen_consumed_credit: false },
  direction_progression: [{ cumulative: 2, increment: 2 }, { cumulative: 5, increment: 3 }, { cumulative: 10, increment: 5 }],
  normative_handbook: 'SCORING.md', methodology: 'GRADING.md', note: 'All atlas routes and overlap/successor/attribution exceptions are normative in SCORING.md. Numerical anchors remain provisional until actual calibration.' };
await writeFile('scoring/rubric-v0.1.yaml', JSON.stringify(rubric, null, 2) + '\n');
